language: node_js
node_js:
  - lts/*
install:
  - npm i -g vuepress
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  fqdn: docs.wappalyzer.com
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
